### ISSUE TITLE
Changelog page repeatedly shown to users

### ISSUE THREAD

**Issue by msramalho** [msramalho/SigTools#53]
I had some conversation feedback on a user receiving notification for the new v3.1.0 version multiple times, not sure why, maybe it would be better to have the changelog as an option in the icon context menu instead of on update... related with #47

**Comment by fabiodrg666** [comment]
This is unexpected behavior. The changelog is shown when chrome triggers the `onInstalled` event. There are a couple of reasons that might trigger this particular event, which could explain this:
- extension update
- extension first-time installation
- **chrome updates**
- when a shared module is updated (not sure what does this mean, perhaps an extension can use other extensions, like add-ons to extensions?)

I would suggest checking what is triggering the event, i.e., only show changelog if and only if the event is triggered because of the first install or extension update.

[Source](https://developer.chrome.com/extensions/runtime#type-OnInstalledReason)

**Comment by fabiodrg666** [comment]
Done. Can I merge into `dev`? This is just an attempt to fix this particular issue. I still think #47 is must-have.

**Comment by msramalho** [comment]
go ahead and merge, #47 can come later.

maybe we should disable changelog in nest preliminary version, what do you think?

**Comment by fabiodrg666** [comment]
Yes, better safe than sorry.
