### ISSUE TITLE
CSS for DataTables library is apparently not loading

### ISSUE THREAD

**Issue by fabiodrg** [msramalho/SigTools#79]
Now:
![image](https://user-images.githubusercontent.com/5472505/96114916-1f902100-0ede-11eb-8810-e54a4c3693c9.png)
![image](https://user-images.githubusercontent.com/5472505/96114984-3898d200-0ede-11eb-83b9-36c61d7cabcb.png)

Expected results:
![image](https://user-images.githubusercontent.com/5472505/96115019-43536700-0ede-11eb-906a-707cde8491a1.png)

Basically, the sorting buttons are there and I click on them, but they are not styled.

**Comment by fabiodrg666** [comment]
Actually, the problem is that DataTable library uses images for the sorting icons, although they don't seem to provide them on the downloads section :shrug: I could extract the images from the live demos and fix the CSS rules to point to the correct location, but I think I will just simply use Unicode characters to present the arrows. That's enough to indicate that columns are sortable and whether a column is sorted ascendingly or descendingly.

**Comment by msramalho** [comment]
Yeah, keeping it simple sounds the way to go here

**Comment by fabiodrg666** [comment]
Thanks for your input! I have some work ready locally, I just need a few minutes to organize the commits and prepare a PR.
Preview:
![image](https://user-images.githubusercontent.com/5472505/96335748-a6760280-1072-11eb-8f01-04d5ebf3c898.png)
